export const GET_CHART_DATA_REQUEST = 'GET_CHART_DATA_REQUEST';
export const GET_CHART_DATA_SUCCESS = 'GET_CHART_DATA_SUCCESS';
export const GET_CHART_DATA_FAILURE = 'GET_CHART_DATA_FAILURE';

export const CLICK_TEST = 'CLICK_TEST';
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
export const ADD_RANDOM_USER = 'ADD_RANDOM_USER';

export const SUBMIT_CONFIG_REQUEST = 'SUBMIT_CONFIG_REQUEST';
export const SUBMIT_CONFIG_SUCCESS = 'SUBMIT_CONFIG_SUCCESS';
export const SUBMIT_CONFIG_FAILURE = 'SUBMIT_CONFIG_FAILURE';

//文章管理页面的action——name
export const CHANGE_STATUS = 'CHANGE_STATUS';
export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_FETCH_TYPE = 'GET_FETCH_TYPE';


